version: '3'
services:
  client:
    build:
      dockerfile: Dockerfile.dev
      context: client
    restart: always
    ports:
      - '4200:4200'
    volumes:
      - /app/node_modules/
      - ./client:/app
  api:
    build:
      dockerfile: Dockerfile.dev
      context: server
    restart: always
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '4000:4000'
    env_file:
      - ./config/dev/api.env
  # tests:
  #   build:
  #     context: server
  #   volumes:
  #     - /app/node_modules
  #     - ./server:/app
  #   env_file:
  #     - ./config/dev/test.env
  #   command: ['npm', 'run', 'test']
  prisma:
    image: prismagraphql/prisma:1.19
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            database: bobalish
            host: host.docker.internal
            port: 5432
            user: postgres
            password: postgres
            migrations: true
            rawAccess: true
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
